# Generated by Django 4.1.4 on 2022-12-09 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('opened', models.DateField(auto_now_add=True)),
                ('state', models.TextField(choices=[('AC', 'Active'), ('FR', 'Frozen'), ('CL', 'Closed')])),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('streetName', models.TextField()),
                ('city', models.CharField(max_length=40)),
                ('zipCode', models.IntegerField()),
            ],
            options={
                'ordering': ['city'],
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FullName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
                ('prenom', models.CharField(max_length=25)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='book',
            name='lang',
        ),
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.book')),
                ('barcode', models.TextField()),
                ('tag', models.TextField()),
                ('title', models.CharField(max_length=50)),
                ('isReferenceOnly', models.BooleanField(default=False)),
                ('lang', models.CharField(choices=[('EN', 'English'), ('FR', 'French'), ('DE', 'German'), ('ES', 'Spanish'), ('IT', 'Italian')], max_length=15)),
                ('numberOfPages', models.IntegerField()),
                ('format', models.TextField(choices=[('PA', 'Paperback'), ('HA', 'Hardcover'), ('AB', 'Audiobook'), ('AC', 'Audio CD'), ('MP', 'MP3 CD'), ('PD', 'PDF')])),
                ('borrowed', models.DateField()),
                ('loanPeriod', models.IntegerField()),
                ('dueDate', models.DateField()),
                ('isOverdue', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['ISBN'],
            },
            bases=('catalog.book',),
        ),
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.account')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.adresse')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.fullname')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('accounts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.account')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.adresse')),
                ('catalog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.catalog')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=25)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.adresse')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.fullname')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='catalog',
            name='records',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.bookitem'),
        ),
        migrations.AddField(
            model_name='account',
            name='borrowed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_requests_created', to='catalog.bookitem'),
        ),
        migrations.AddField(
            model_name='account',
            name='reserved',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.bookitem'),
        ),
    ]
