# Generated by Django 4.1.4 on 2022-12-18 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_account_adresse_catalog_fullname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='books',
        ),
    ]
